---
- import_tasks: nvidia_nonfree.yml

- name: enable bumblebee repo
  become: yes
  yum_repository:
    name: chenxiaolong_bumblebee
    description: copr for bumblebee
    baseurl: https://copr-be.cloud.fedoraproject.org/results/chenxiaolong/bumblebee/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/chenxiaolong/bumblebee/pubkey.gpg
    skip_if_unavailable: yes

- name: install bumblebee
  become: yes
  package:
    name:
      - akmod-bbswitch
      - bumblebee
      - primus
    state: present
  register: bumblebee_packages

- name: reload systemd daemon
  become: yes
  when: bumblebee_packages.changed
  systemd:
    daemon_reload: yes

- name: enable bumblebee
  become: yes
  systemd:
    name: bumblebeed
    masked: no
    enabled: yes

- name: disable nouveau fallback
  become: yes
  systemd:
    name: nvidia-fallback
    masked: yes
    state: stopped

- name: add user to bumblebee group
  become: yes
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups:
      - bumblebee
