---
- import_tasks: rpmfusion_nonfree.yml

- name: install Nvidia nonfree drivers
  become: yes
  package:
    name:
      - xorg-x11-drv-nvidia
      - xorg-x11-drv-nvidia-cuda
      - akmod-nvidia
      - acpi
    state: present
