---
- name: check if non-free rpmfusion repo is already installed
  stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree.repo
  register: rpmfusion_nonfree

- name: install rpmfusion repos
  become: yes
  when: not rpmfusion_nonfree.stat.exists
  package:
    name: "https://download1.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ ansible_facts['distribution_version'] }}.noarch.rpm"
    state: present
  loop:
    - free
    - nonfree
