#!/usr/bin/env sh

cd ~/.aviary || exit 1

if [ ! -d ~/.local/share/aviary ]
then
  mkdir -p ~/.local/share/aviary
fi

if [ ! -f ~/.local/share/aviary/bin/activate ]
then
  python3 -m venv ~/.local/share/aviary
fi

. ~/.local/share/aviary/bin/activate

if ! command -v ansible-playbook >/dev/null
then
  pip install ansible ansible-lint
fi

subcmd="$1"
shift

with_ansible_vars() {
  "$@" -i "$(hostname -s)," -e "ansible_connection=local" -e "ansible_python_interpreter=$(command -v python)"
}

case "$subcmd" in
  run)
    sudo -v
    with_ansible_vars ansible-playbook "src/$(hostname -s).yml" "$@";;
  facts)
    with_ansible_vars ansible -m setup "$(hostname -s)";;
  retry)
    "$0" run --limit "@${HOME}/.ansible-retry-aviary/$(hostname -s).retry"
    ;;
  code)
    code .;;
  lint)
    echo "TODO";;
  *)
    echo "unknown command"
    exit 1;;
esac
