#!/usr/bin/env sh

cd ~/.aviary || exit 1

if ! command -v pipsi >/dev/null; then
  pip3 install --user pipsi || pip install --user pipsi
fi

if ! command -v ansible >/dev/null; then
  pipsi install ansible
  pipsi install ansible-lint
  pipsi install molecule
fi

python_interpreter() {
  if [ -x /usr/bin/python3 ]; then
    echo "/usr/bin/python3"
  else
    command -v python3 || command -v python
  fi
}

with_ansible_vars() {
  "$@" -i "$(hostname -s)," -e "ansible_connection=local" -e "ansible_python_interpreter=$(python_interpreter)"
}

subcmd="$1"
shift

case "$subcmd" in
  run)
    sudo -v
    with_ansible_vars ansible-playbook "src/$(hostname -s).yml" "$@";;
  facts)
    with_ansible_vars ansible -m setup "$(hostname -s)";;
  retry)
    "$0" run --limit "@${HOME}/.ansible-retry-aviary/$(hostname -s).retry"
    ;;
  code)
    code .;;
  update)
    git pull && ./aviary run;;
  local-update)
    ! command -v dnf >/dev/null || dnf upgrade -y
    ! command -v apt-get >/dev/null || ( apt-get update && apt-get upgrade -y )
    brew update
    brew upgrade
    brew cask upgrade;;
  lint)
    echo "TODO";;
  *)
    echo "unknown command"
    exit 1;;
esac
