---
- name: install preferred fonts on Ubuntu
  when: ansible_facts['distribution'] == 'Ubuntu'
  become: true
  package:
    state: present
    name:
      - fonts-roboto
      - fonts-noto
      - fonts-ubuntu
