---
- name: install expected packages
  become: yes
  package:
    name:
      - "@development-tools"
      - git
      - fish
      - vim
      - zeal
      - libxcrypt-compat
    state: present

- name: create fish config directories
  file:
    path: ~/.config/fish/conf.d
    state: directory

- name: add fisher config
  copy:
    src: "{{ item.key }}"
    dest: "{{ item.value }}"
  loop:
    - key: install-fisher.fish
      value: "~/.config/fish/conf.d/install-fisher.fish"
    - key: fishfile
      value: "~/.config/fish/fishfile"

- name: general fish config
  copy:
    src: "{{ item }}"
    dest: "~/.config/fish/conf.d/{{ item }}"
  loop:
    - local-bin.fish

- name: linux specific fish config
  when: ansible_facts['system'] == "Linux"
  copy:
    src: "{{ item }}"
    dest: "~/.config/fish/conf.d/{{ item }}"
  loop:
    - linux-homebrew.fish
    - linux-snap.fish

- name: install vscode
  become: yes
  snap:
    name: code
    classic: yes
    state: present
