---
- name: install brew packages
  homebrew:
    path: "/home/linuxbrew/.linuxbrew/bin:/usr/local/bin"
    name:
      - adr-tools
      - awscli
      - bat
      - cloc
      - fish
      - fzf
      - git
      - gnupg
      - golang
      - httpie
      - hub
      - jq
      - node-build
      - nodenv
      - puma/puma/puma-dev
      - pyenv
      - rbenv
      - ripgrep
      - rsync
      - ruby-build
      - rustup-init
      - shfmt
      - vim
      - xsv

- name: install rustup
  command: rustup-init --default-toolchain stable --no-modify-path -y
  args:
    creates: ~/.rustup
