---
- name: install brew packages
  homebrew:
    path: "/home/linuxbrew/.linuxbrew/bin:/usr/local/bin"
    name:
      - adr-tools
      - awscli
      - fish
      - fzf
      - git
      - gnupg
      - goenv
      - heroku
      - httpie
      - hub
      - jq
      - node-build
      - nodenv
      - pet
      - pyenv
      - rbenv
      - ripgrep
      - ruby-build
      - shfmt
      - vim
      - xsv
      - cloc
      - rustup-init

- name: install rustup
  command: rustup-init --default-toolchain stable --no-modify-path -y
  args:
    creates: ~/.rustup
