---
- name: create fish config directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.config/fish/conf.d
    - ~/.config/fish/functions

- name: add fish config files
  copy:
    src: "{{ item.from }}"
    dest: "~/.config/fish/{{ item.to }}"
    mode: 0700
  loop:
    - from: shell/fishfile
      to: fishfile
    - from: shell/conf.d/
      to: conf.d/
    - from: shell/functions/
      to: functions/
