---
- name: brew upgrade
  homebrew:
    path: "/home/linuxbrew/.linuxbrew/bin:/usr/local/bin"
    update_homebrew: yes
    upgrade_all: yes

- name: brew cask upgrade
  when: ansible_facts['os_family'] == 'Darwin'
  homebrew_cask:
    update_homebrew: yes
    upgrade_all: yes

- name: dnf upgrade
  when: ansible_facts['os_family'] == 'RedHat'
  become: yes
  dnf:
    name: '*'
    state: latest
