---
- name: install expected packages
  package:
    name:
      - "@development-tools"
      - git
      - fish
      - vim
    state: present

- name: install vscode
  snap:
    name: code
    classic: yes
    state: present
