---
- name: determine virtualization packages
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_release'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"

- name: install virtualization packages
  become: true
  package:
    state: present
    name: "{{ machine_virt_packages }}"

- name: install gui virtualization packages
  become: true
  when: virtualization_include_gui
  package:
    state: present
    name: "{{ machine_virt_gui_packages }}"
