---
# - import_playbook: meta_plays/core.yml

- name: configure machine
  hosts: owl
  roles:
    - name: prereqs
    - name: fonts
    - name: interactivity
    - name: appearance.budgie
    - name: security
    - name: virtualization
      vars:
        virtualization_include_gui: true
    - name: shell
    - name: apps.devtools
    - name: apps.vscode
    - name: apps.pyenv
    - name: apps.rbenv
    - name: apps.nodenv
    - name: apps.misc

# - name: install machine-specific packages
#   become: true
#   hosts: owl
#   tasks:
#     - name: install extra packages
#       package:
#         state: present
#         name: "{{ host_extra_packages }}"
# 
# - name: setup machine
#   hosts: owl
#   tasks:
#     - import_tasks: nix_dev_machine.yml
